export const proffessorsList = [
  {
    id: 1,
    name: '유희경',
    surname: '교수',
    title1: '컴퓨터보안/빅데이터/전산통계학',

    title2: '5공학관 417호',
    title3: '033-570-6371',
    title4: ' hkyoo@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBlKA&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_267_1632459664000.do',
  },
  {
    id: 2,
    name: '황득영',
    surname: '교수',
    title1: '병렬컴파일러/프로그래밍언어론',
    title2: '5공학관 514호',
    title3: '033-570-6376',
    title4: 'dyhwang@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBmwJiA&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_272_1632460249000.do',
  },
  {
    id: 3,
    name: '홍종성',
    surname: '교수',
    title1: '음향공학/영상공학/문화기술연구',
    title2: '5공학관 510호',
    title3: '033-570-6373',
    title4: 'jshong@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: ' https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBmCYBYg&',
    img: 'https://aisw.kangwon.ac.kr/_attach/gyosupic/10124.jpg',
  },
  {
    id: 4,
    name: '오형술 ',
    surname: '교수',
    title1: 'PSS설계/SCM/네트워크 신뢰도',
    title2: '5공학관 509호',
    title3: '033-570-6584',
    title4: 'hsoh@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBmGZiA&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_264_1632459425000.do',
  },
  {
    id: 5,
    name: '장영관 ',
    surname: '교수',
    title1: '물류정보시스템/MIS/ERP/SCM/인간공학',
    title2: '5공학관 507호',
    title3: '033-570-6585',
    title4: 'ykjang@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBmBYGYg&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_265_1632459459000.do',
  },

  {
    id: 6,
    name: '문성동 ',
    surname: '교수',
    title1: '생산기계/공장자동화',
    title2: '5공학관 508호',
    title3: '033-570-6586',
    title4: 'sudom@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwBmFYA4g&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_266_1632459636000.do',
  },

  {
    id: 7,
    name: '윤인섭',
    surname: '교수',
    title1: '자성체/방송조명/뉴미디어',
    title2: '5공학관 515호',
    title3: '033-570-6374',
    title4: 'isyoon@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: ' https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$KwBgjCJA&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_270_1632460204000.do',
  },

  {
    id: 8,
    name: '윤종철',
    surname: '부교수',
    title1: '영상처리, 가상/증강현실',
    title2: '5공학관 609호',
    title3: '033-570-6869',
    title4: 'media19@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwjMCYg&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_269_1632460183000.do',
  },

  {
    id: 9,
    name: '박은희',
    surname: '조교수',
    title1: '응용수학/수치해석, 데이터과학',
    title2: '5공학관 513호',
    title3: '033-570-6372',
    title4: 'eh.park@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwisBYg&',
    img: 'https://aisw.kangwon.ac.kr/_attach/gyosupic/11154.jpg',
  },

  {
    id: 10,
    name: '이두호',
    surname: '부교수',
    title1: '대기행렬 시스템/최적화/게임이론',
    title2: '5공학관 506호',
    title3: '033-570-6583',
    title4: 'enjdhlee@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwicyA&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_273_1632460345000.do',
  },

  {
    d: 11,
    name: '이두호',
    surname: '부교수',
    title1: '임베디드 시스템 / 소프트웨어, 비휘발성 메모리',
    title2: '5공학관 415호',
    title3: '033-570-6377',
    title4: 'sjkwon@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://scholar.google.com/citations?user=XthdAdMAAAAJ&hl=ko',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_268_1632460166000.do',
  },
  {
    id: 12,
    name: '이태민',
    surname: '조교수',
    title1: '컴퓨터그래픽스,감성컴퓨팅,증강/가상현실,인공지능',
    title2: '5공학관 416호',
    title3: '033-570-6378',
    title4: 'kevinlee@kangwon.ac.kr',
    imgUrl: 'https:blablabla..com',
    Link: 'https://aisw.kangwon.ac.kr/aisw/professor/professor.do?mode=view&key=$cms$IwdgzAnCQ&',
    img: 'https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_664_1646725165000.do',
  },
];
